# Generated by Django 4.2.3 on 2023-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='google_maps_link',
            field=models.URLField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='route',
            name='ride_fee',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='route',
            name='midway_stations',
            field=models.ManyToManyField(related_name='routes', to='api.midwaystation'),
        ),
    ]
