# Generated by Django 4.2.3 on 2023-07-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='ride_fee',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
