# Generated by Django 4.2.3 on 2023-07-20 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_route_ride_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\u0600-\\u06FF\\s]+$', 'Only Arabic and English letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\u0600-\\u06FF\\s]+$', 'Only Arabic and English letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='ride_fee',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
