# Generated by Django 4.2.3 on 2023-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_midwaystation_route_google_maps_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='midway_station',
        ),
        migrations.AddField(
            model_name='route',
            name='midway_stations',
            field=models.ManyToManyField(related_name='routes', to='api.midwaystation'),
        ),
    ]
