# Generated by Django 4.2.3 on 2023-07-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_route_midway_station_route_midway_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='midway_stations',
            field=models.ManyToManyField(blank=True, related_name='routes', to='api.midwaystation'),
        ),
    ]
