# Generated by Django 4.2.3 on 2023-07-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_route_destination_alter_route_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMidwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midway_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.midwaystation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='midway_stations',
            field=models.ManyToManyField(blank=True, related_name='routes', through='api.RouteMidwayStation', to='api.midwaystation'),
        ),
    ]
